#!/usr/bin/env node
/**
 * BLOCK MANIFEST GENERATOR — the single source of truth for "what blocks exist".
 *
 * Writes BLOCKS.md (for humans and agents) and blocks.json (for tooling) straight from the
 * registries in src/blocks/. Run it after adding a block:
 *
 *   npm run blocks
 *
 * WHY IT PARSES INSTEAD OF IMPORTS: the registries are .tsx and pull in src/lib/fonts.ts, which
 * calls loadFont() at module scope. That needs a browser, so a plain `node --import` of the
 * registry explodes. Parsing keeps the generator dependency-free and runnable anywhere.
 *
 * WHY IT EXISTS AT ALL: the catalog used to live in four places that could disagree — the two
 * .tsx registries, a UI list inside site/main.tsx, and hand-written prose tables in SKILL.md.
 * They did disagree: 24 spec files with 17 registered, and a skill law recommending transitions
 * that were never implemented as blocks. Generated inventory cannot drift.
 */
import {readFileSync, readdirSync, writeFileSync} from 'fs';
import {join} from 'path';
import {fileURLToPath} from 'url';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const SRC = join(ROOT, 'src', 'blocks');
const read = (...p) => readFileSync(join(SRC, ...p), 'utf8');

// Pull `key: 'value'` / `key: 123` out of one object literal.
const field = (body, key) => {
  const m =
    body.match(new RegExp(`\\b${key}\\s*:\\s*'((?:[^'\\\\]|\\\\.)*)'`)) ||
    body.match(new RegExp(`\\b${key}\\s*:\\s*"((?:[^"\\\\]|\\\\.)*)"`)) ||
    body.match(new RegExp(`\\b${key}\\s*:\\s*([A-Za-z0-9_.]+)`));
  return m ? m[1].replace(/\\'/g, "'") : undefined;
};

// Split an exported `const NAME: Block[] = [ ... ]` into its top-level object literals.
const entries = (src, arrayName) => {
  const start = src.indexOf(`${arrayName}: Block[] = [`);
  if (start === -1) return [];
  let depth = 0;
  // seek the '[' of "= [", NOT the one inside "Block[]" — that one is immediately closed by ']'
  // at depth 0 and aborts the scan, which is how this first returned zero blocks.
  let i = src.indexOf('= [', start) + 2;
  const out = [];
  let buf = null;
  for (; i < src.length; i++) {
    const c = src[i];
    if (c === '{') {
      if (depth === 0) buf = '';
      depth++;
    }
    if (depth > 0) buf += c;
    if (c === '}') {
      depth--;
      if (depth === 0) {
        out.push(buf);
        buf = null;
      }
    }
    if (c === ']' && depth === 0) break;
  }
  return out;
};

const parse = (src, arrayName, category) =>
  entries(src, arrayName).map((b) => ({
    name: field(b, 'name'),
    category: field(b, 'category') || category,
    tag: field(b, 'tag') || null,
    source: field(b, 'source'),
    desc: field(b, 'desc'),
    durationInFrames: Number(field(b, 'durationInFrames')) || null,
    fps: /fps:\s*FPS/.test(b) ? 60 : Number(field(b, 'fps')) || null,
  }));

// ── transitions + ui: parsed from their registry arrays ─────────────────────
const transitions = parse(read('transitions.tsx'), 'TRANSITION_BLOCKS', 'transition');
const ui = parse(read('ui-motion.tsx'), 'UI_BLOCKS', 'ui');

// ── typography: generated from the spec JSONs the registry actually imports ──
const atDir = join(SRC, 'animate-text');
const atIndex = readFileSync(join(atDir, 'index.tsx'), 'utf8');
const registeredSpecs = [...atIndex.matchAll(/from '\.\/specs\/([\w-]+)\.json'/g)].map((m) => m[1]);
const specFiles = readdirSync(join(atDir, 'specs')).filter((f) => f.endsWith('.json')).map((f) => f.replace(/\.json$/, ''));
const orphanSpecs = specFiles.filter((s) => !registeredSpecs.includes(s));

const typography = registeredSpecs.map((id) => {
  const spec = JSON.parse(readFileSync(join(atDir, 'specs', `${id}.json`), 'utf8'));
  return {
    name: spec.id ?? id,
    category: 'typography',
    tag: null,
    source: 'animate-text',
    desc: spec.description ?? '',
    target: spec.target ?? null,
    durationInFrames: null,
    fps: 30,
  };
});

const groups = [
  {label: 'Transition', category: 'transition', note: 'scene-to-scene glue', blocks: transitions},
  {label: 'Typography', category: 'typography', note: 'pixel-point/animate-text', blocks: typography},
  {label: 'UI motion', category: 'ui', note: 'GPT-5.5 house standard', blocks: ui},
];
const all = groups.flatMap((g) => g.blocks);

// ── blocks.json ─────────────────────────────────────────────────────────────
writeFileSync(
  join(ROOT, 'blocks.json'),
  JSON.stringify({generated: 'npm run blocks', total: all.length, orphanSpecs, groups}, null, 2) + '\n'
);

// ── BLOCKS.md ───────────────────────────────────────────────────────────────
const esc = (s = '') => s.replace(/\|/g, '\\|');
let md = `# Block catalog

<!-- GENERATED by \`npm run blocks\` from src/blocks/ — do not edit by hand. -->

**${all.length} blocks.** This file is the authoritative inventory: the skill reads it to choose
blocks, so it can never drift from what is actually implemented. Compose a video by picking one
**object** (typography or UI), a **transition** for each handoff, and — per the VARY laws — at
least two distinct text animations and a different primary handoff than the previous video.

Transitions are tagged \`intro\` (enter half), \`outro\` (exit half) or \`full-tro\` (a matched pair).
Pair an outro with an intro on the **same axis**: \`push-off-left\`/\`glide-in\` are X,
\`scale-up-cut\`/\`scale-pop-in\` are Z.
`;

for (const g of groups) {
  md += `\n## ${g.label} — ${g.blocks.length} blocks\n\n_${g.note}_\n\n`;
  md += `| block | tag | length | source | what it does |\n|---|---|---|---|---|\n`;
  for (const b of g.blocks) {
    const len = b.durationInFrames && b.fps ? `${(b.durationInFrames / b.fps).toFixed(2)}s @${b.fps}fps` : '—';
    md += `| \`${b.name}\` | ${b.tag ?? '—'} | ${len} | ${esc(b.source)} | ${esc(b.desc)} |\n`;
  }
}

if (orphanSpecs.length) {
  md += `\n## ⚠ Unregistered specs (${orphanSpecs.length})\n
These JSON specs exist in \`src/blocks/animate-text/specs/\` but are **not** registered in
\`index.tsx\`, so they are not usable blocks. Either register them or record why they are excluded
— a spec the skill can name but not render is worse than one that does not exist.\n\n`;
  for (const s of orphanSpecs) md += `- \`${s}\`\n`;
}

writeFileSync(join(ROOT, 'BLOCKS.md'), md);
console.log(`✓ blocks: ${all.length} (${transitions.length} transition, ${typography.length} typography, ${ui.length} ui)` +
  (orphanSpecs.length ? ` · ⚠ ${orphanSpecs.length} unregistered spec(s)` : ''));
